name: Publish Images to Container Registries

on:
  release:
    types: [ released ]
  push:
    branches: [ main ]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine Docker tag
        run: |
          DOCKER_TAG=`git describe --tags --always`
          echo "docker_tag=${DOCKER_TAG}" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push development images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: |
            simonsobs/scheduler-server:${{ env.docker_tag }}
            ghcr.io/simonsobs/scheduler-server:${{ env.docker_tag }}

      - name: Build and push release images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name == 'release' }}
          tags: |
            simonsobs/scheduler-server:latest
            simonsobs/scheduler-server:${{ env.docker_tag }}
            ghcr.io/simonsobs/scheduler-server:latest
            ghcr.io/simonsobs/scheduler-server:${{ env.docker_tag }}

